name: Wasm Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: wasm-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-check-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2
        with:
          key: wasm-check-wasm32-wasip1
      - run: cargo check --target wasm32-wasip1 --no-default-features --features wasm --lib
